language: php

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.6
    - php: 7
    - php: hhvm

install:
  - composer install
  - mkdir -p build/logs

script: vendor/bin/phpunit

after_success:
  - if [[ "$TRAVIS_PHP_VERSION" == "5.5" ]]; then vendor/bin/coveralls ; fi
